globalThis.facebookURL = "#";
globalThis.PinterestURL = "#";
globalThis.twitterURL = "#";
globalThis.redditURL = "#";
globalThis.siteUrl = "https:\/\/www.myrecipes.com";
globalThis.homepageTitle = "PIN RECIPES";
globalThis.homepageTagline = "Pin Recipes - Discover delicious recipes for every occasion";
globalThis.email = 'contact@myrecipes.com';
globalThis.copyright = "2025 - 2026 PIN RECIPES. All rights reserved.";
